# Generated by Django 4.1.1 on 2022-09-09 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('login', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('profile_image', models.ImageField(blank=True, default='media/default_profile_image', max_length=255, null=True, upload_to='media/profile_images')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('picture', models.ImageField(blank=True, default='media/default_post_image', max_length=255, null=True, upload_to='media/post_images')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.user')),
            ],
        ),
    ]
